sudo: required
language: node_js
node_js:
  - 10
services:
    - docker

before_install:
     - docker build -f Dockerfile.dev -t raunakjodhawat/chuck-norris-client:latest .

deploy:
    edge: true
    provide: elasticbeanstalk
    region: "us-east-2"
    app: "Chuck Norris Jokes"
    env: "ChuckNorrisJokes-env"
    bucket_name: "elasticbeanstalk-us-east-2-681334850105"
    bucket_path: "docker-multi"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_CODE
    secret_access_key: "$AWS_SECRET_CODE"