sudo: required
services:
    - docker

before_install:
     - docker build -t raunakjodhawat/chucknorris:latest .

script:
    - docker run -e CI=true raunakjodhawat/chuckNorris npm run test -- --coverage

deploy:
    edge: true
    provide: elasticbeanstalk
    region: "us-east-2"
    app: "Chuck Norris Jokes"
    env: "ChuckNorrisJokes-env"
    bucket_name: "elasticbeanstalk-us-east-2-681334850105"
    bucket_path: "docker-multi"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_CODE
    secret_access_key: "$AWS_SECRET_CODE"